// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: game/id.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息id(10000 - 9999999)
type ID int32

const (
	ID_ID_GAME_None ID = 0
	// system
	ID_ID_C2S_Ping             ID = 10000 // ping
	ID_ID_S2C_Ping             ID = 10001 // pong
	ID_ID_C2S_AnnouncementList ID = 10010 // 公告列表
	ID_ID_S2C_AnnouncementList ID = 10011 // 公告列表返回
	ID_ID_C2S_Login            ID = 10100 // 登录
	ID_ID_S2C_Login            ID = 10101 // 登录返回
	ID_ID_C2S_Logout           ID = 10102 // 登出
	ID_ID_S2C_Logout           ID = 10103 // 登出返回
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		0:     "ID_GAME_None",
		10000: "ID_C2S_Ping",
		10001: "ID_S2C_Ping",
		10010: "ID_C2S_AnnouncementList",
		10011: "ID_S2C_AnnouncementList",
		10100: "ID_C2S_Login",
		10101: "ID_S2C_Login",
		10102: "ID_C2S_Logout",
		10103: "ID_S2C_Logout",
	}
	ID_value = map[string]int32{
		"ID_GAME_None":            0,
		"ID_C2S_Ping":             10000,
		"ID_S2C_Ping":             10001,
		"ID_C2S_AnnouncementList": 10010,
		"ID_S2C_AnnouncementList": 10011,
		"ID_C2S_Login":            10100,
		"ID_S2C_Login":            10101,
		"ID_C2S_Logout":           10102,
		"ID_S2C_Logout":           10103,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_game_id_proto_enumTypes[0].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_game_id_proto_enumTypes[0]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_game_id_proto_rawDescGZIP(), []int{0}
}

var File_game_id_proto protoreflect.FileDescriptor

var file_game_id_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x2a, 0xc4, 0x01, 0x0a, 0x02, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x0c, 0x49, 0x44, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0b, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x69, 0x6e, 0x67,
	0x10, 0x90, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x69,
	0x6e, 0x67, 0x10, 0x91, 0x4e, 0x12, 0x1c, 0x0a, 0x17, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x10, 0x9a, 0x4e, 0x12, 0x1c, 0x0a, 0x17, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x9b,
	0x4e, 0x12, 0x11, 0x0a, 0x0c, 0x49, 0x44, 0x5f, 0x43, 0x32, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x10, 0xf4, 0x4e, 0x12, 0x11, 0x0a, 0x0c, 0x49, 0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x10, 0xf5, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x49, 0x44, 0x5f, 0x43, 0x32,
	0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x10, 0xf6, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x49,
	0x44, 0x5f, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x10, 0xf7, 0x4e, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_id_proto_rawDescOnce sync.Once
	file_game_id_proto_rawDescData = file_game_id_proto_rawDesc
)

func file_game_id_proto_rawDescGZIP() []byte {
	file_game_id_proto_rawDescOnce.Do(func() {
		file_game_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_id_proto_rawDescData)
	})
	return file_game_id_proto_rawDescData
}

var file_game_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_id_proto_goTypes = []interface{}{
	(ID)(0), // 0: game_id.ID
}
var file_game_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_id_proto_init() }
func file_game_id_proto_init() {
	if File_game_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_id_proto_goTypes,
		DependencyIndexes: file_game_id_proto_depIdxs,
		EnumInfos:         file_game_id_proto_enumTypes,
	}.Build()
	File_game_id_proto = out.File
	file_game_id_proto_rawDesc = nil
	file_game_id_proto_goTypes = nil
	file_game_id_proto_depIdxs = nil
}
