// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: game/msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @id: 10000
type C2S_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_Ping) Reset() {
	*x = C2S_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Ping) ProtoMessage() {}

func (x *C2S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Ping.ProtoReflect.Descriptor instead.
func (*C2S_Ping) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{0}
}

// @id: 10001
type S2C_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"` // 服务器时间戳
}

func (x *S2C_Ping) Reset() {
	*x = S2C_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Ping) ProtoMessage() {}

func (x *S2C_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Ping.ProtoReflect.Descriptor instead.
func (*S2C_Ping) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_Ping) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// @id: 10010
type C2S_AnnouncementList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
}

func (x *C2S_AnnouncementList) Reset() {
	*x = C2S_AnnouncementList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_AnnouncementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AnnouncementList) ProtoMessage() {}

func (x *C2S_AnnouncementList) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AnnouncementList.ProtoReflect.Descriptor instead.
func (*C2S_AnnouncementList) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_AnnouncementList) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// @id: 10011
type S2C_AnnouncementList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Announcement []string `protobuf:"bytes,1,rep,name=Announcement,proto3" json:"Announcement,omitempty"`
}

func (x *S2C_AnnouncementList) Reset() {
	*x = S2C_AnnouncementList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_AnnouncementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AnnouncementList) ProtoMessage() {}

func (x *S2C_AnnouncementList) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AnnouncementList.ProtoReflect.Descriptor instead.
func (*S2C_AnnouncementList) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_AnnouncementList) GetAnnouncement() []string {
	if x != nil {
		return x.Announcement
	}
	return nil
}

type C2S_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_Login) Reset() {
	*x = C2S_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Login) ProtoMessage() {}

func (x *C2S_Login) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Login.ProtoReflect.Descriptor instead.
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{4}
}

type S2C_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_Login) Reset() {
	*x = S2C_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Login) ProtoMessage() {}

func (x *S2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Login.ProtoReflect.Descriptor instead.
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{5}
}

type C2S_Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_Logout) Reset() {
	*x = C2S_Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Logout) ProtoMessage() {}

func (x *C2S_Logout) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Logout.ProtoReflect.Descriptor instead.
func (*C2S_Logout) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{6}
}

type S2C_Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_Logout) Reset() {
	*x = S2C_Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Logout) ProtoMessage() {}

func (x *S2C_Logout) ProtoReflect() protoreflect.Message {
	mi := &file_game_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Logout.ProtoReflect.Descriptor instead.
func (*S2C_Logout) Descriptor() ([]byte, []int) {
	return file_game_msg_proto_rawDescGZIP(), []int{7}
}

var File_game_msg_proto protoreflect.FileDescriptor

var file_game_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0x0a, 0x0a, 0x08, 0x43, 0x32,
	0x53, 0x5f, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x14, 0x43, 0x32, 0x53, 0x5f, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x53, 0x32,
	0x43, 0x5f, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22, 0x0c,
	0x0a, 0x0a, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_msg_proto_rawDescOnce sync.Once
	file_game_msg_proto_rawDescData = file_game_msg_proto_rawDesc
)

func file_game_msg_proto_rawDescGZIP() []byte {
	file_game_msg_proto_rawDescOnce.Do(func() {
		file_game_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_msg_proto_rawDescData)
	})
	return file_game_msg_proto_rawDescData
}

var file_game_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_msg_proto_goTypes = []interface{}{
	(*C2S_Ping)(nil),             // 0: game_msg.C2S_Ping
	(*S2C_Ping)(nil),             // 1: game_msg.S2C_Ping
	(*C2S_AnnouncementList)(nil), // 2: game_msg.C2S_AnnouncementList
	(*S2C_AnnouncementList)(nil), // 3: game_msg.S2C_AnnouncementList
	(*C2S_Login)(nil),            // 4: game_msg.C2S_Login
	(*S2C_Login)(nil),            // 5: game_msg.S2C_Login
	(*C2S_Logout)(nil),           // 6: game_msg.C2S_Logout
	(*S2C_Logout)(nil),           // 7: game_msg.S2C_Logout
}
var file_game_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_msg_proto_init() }
func file_game_msg_proto_init() {
	if File_game_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_AnnouncementList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_AnnouncementList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_msg_proto_goTypes,
		DependencyIndexes: file_game_msg_proto_depIdxs,
		MessageInfos:      file_game_msg_proto_msgTypes,
	}.Build()
	File_game_msg_proto = out.File
	file_game_msg_proto_rawDesc = nil
	file_game_msg_proto_goTypes = nil
	file_game_msg_proto_depIdxs = nil
}
