
# 集群配置

# rpc监听
RPCServer:
  # 监听地址
  Addr: 0.0.0.0:6688
  # 协议
  Protoc: "tcp"
  # 最大rpc参数长度(默认 2097152=2M)
  MaxRpcParamLen: 2097152
  # 压缩参数,消息长度超过该值,将进行压缩(默认 1048576=1M)
  CompressBytesLen: 1048576

# 负载均衡策略
ServiceLoadStrategy:
#  Rank: 4


ETCDConf:
  # etcd地址
  EtcdEndPoints:
    - 127.0.0.1:2379
  # 服务发现的监听路径
  DiscoveryPath: /server/service
  TTLSecond: 30s
  DialTimeout: 3s
  # etcd用户名
  UserName: root
  # etcd密码
  Password: 123456