// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: comm/comm.proto

package commmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatus int32

const (
	ServerStatus_Normal      ServerStatus = 0 // 正常
	ServerStatus_Maintenance ServerStatus = 1 // 维护中
	ServerStatus_Close       ServerStatus = 2 // 关闭
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "Normal",
		1: "Maintenance",
		2: "Close",
	}
	ServerStatus_value = map[string]int32{
		"Normal":      0,
		"Maintenance": 1,
		"Close":       2,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_comm_comm_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_comm_comm_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{0}
}

var File_comm_comm_proto protoreflect.FileDescriptor

var file_comm_comm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x2a, 0x36,
	0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a,
	0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x61,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x10, 0x02, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_comm_proto_rawDescOnce sync.Once
	file_comm_comm_proto_rawDescData = file_comm_comm_proto_rawDesc
)

func file_comm_comm_proto_rawDescGZIP() []byte {
	file_comm_comm_proto_rawDescOnce.Do(func() {
		file_comm_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_comm_proto_rawDescData)
	})
	return file_comm_comm_proto_rawDescData
}

var file_comm_comm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_comm_comm_proto_goTypes = []interface{}{
	(ServerStatus)(0), // 0: common_comm.ServerStatus
}
var file_comm_comm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comm_comm_proto_init() }
func file_comm_comm_proto_init() {
	if File_comm_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_comm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_comm_proto_goTypes,
		DependencyIndexes: file_comm_comm_proto_depIdxs,
		EnumInfos:         file_comm_comm_proto_enumTypes,
	}.Build()
	File_comm_comm_proto = out.File
	file_comm_comm_proto_rawDesc = nil
	file_comm_comm_proto_goTypes = nil
	file_comm_comm_proto_depIdxs = nil
}
