// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: comm/errcode.proto

package commmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Ok                 ErrCode = 0
	ErrCode_ApiNotFound        ErrCode = 1   // 接口不存在
	ErrCode_ApiError           ErrCode = 2   // 接口运行报错
	ErrCode_ApiRunTimeout      ErrCode = 3   // 接口运行超时
	ErrCode_ApiDeveloping      ErrCode = 4   // 接口正在开发中
	ErrCode_ParamsInvalid      ErrCode = 10  // 参数错误
	ErrCode_SdkNotFound        ErrCode = 11  // sdk不存在
	ErrCode_UserNotFound       ErrCode = 100 // 用户不存在
	ErrCode_UserStatusAbnormal ErrCode = 101 // 用户状态异常
	ErrCode_TokenCreateFailed  ErrCode = 102 // token创建失败
	ErrCode_TokenInvalid       ErrCode = 103 // token无效
	ErrCode_TokenExpired       ErrCode = 104 // token过期
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:   "Ok",
		1:   "ApiNotFound",
		2:   "ApiError",
		3:   "ApiRunTimeout",
		4:   "ApiDeveloping",
		10:  "ParamsInvalid",
		11:  "SdkNotFound",
		100: "UserNotFound",
		101: "UserStatusAbnormal",
		102: "TokenCreateFailed",
		103: "TokenInvalid",
		104: "TokenExpired",
	}
	ErrCode_value = map[string]int32{
		"Ok":                 0,
		"ApiNotFound":        1,
		"ApiError":           2,
		"ApiRunTimeout":      3,
		"ApiDeveloping":      4,
		"ParamsInvalid":      10,
		"SdkNotFound":        11,
		"UserNotFound":       100,
		"UserStatusAbnormal": 101,
		"TokenCreateFailed":  102,
		"TokenInvalid":       103,
		"TokenExpired":       104,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_comm_errcode_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_comm_errcode_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_comm_errcode_proto_rawDescGZIP(), []int{0}
}

var File_comm_errcode_proto protoreflect.FileDescriptor

var file_comm_errcode_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x2a, 0xdf, 0x01, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x70, 0x69, 0x4e,
	0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x70, 0x69,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x70, 0x69, 0x52, 0x75,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x70,
	0x69, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x10, 0x04, 0x12, 0x11, 0x0a,
	0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x0a,
	0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x64, 0x6b, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10,
	0x0b, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e,
	0x64, 0x10, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x66, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x10, 0x67, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x64, 0x10, 0x68, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_errcode_proto_rawDescOnce sync.Once
	file_comm_errcode_proto_rawDescData = file_comm_errcode_proto_rawDesc
)

func file_comm_errcode_proto_rawDescGZIP() []byte {
	file_comm_errcode_proto_rawDescOnce.Do(func() {
		file_comm_errcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_errcode_proto_rawDescData)
	})
	return file_comm_errcode_proto_rawDescData
}

var file_comm_errcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_comm_errcode_proto_goTypes = []interface{}{
	(ErrCode)(0), // 0: common_errcode.ErrCode
}
var file_comm_errcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comm_errcode_proto_init() }
func file_comm_errcode_proto_init() {
	if File_comm_errcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_errcode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_errcode_proto_goTypes,
		DependencyIndexes: file_comm_errcode_proto_depIdxs,
		EnumInfos:         file_comm_errcode_proto_enumTypes,
	}.Build()
	File_comm_errcode_proto = out.File
	file_comm_errcode_proto_rawDesc = nil
	file_comm_errcode_proto_goTypes = nil
	file_comm_errcode_proto_depIdxs = nil
}
