// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: login/id.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息id(1 - 9999)
type MsgId int32

const (
	MsgId_Msg_None MsgId = 0
	// system
	MsgId_C2S_SignIn           MsgId = 1  // 登录
	MsgId_C2S_DeleteAccount    MsgId = 2  // 删除账号(删除账号会有一个反悔期,在反悔期内登录账号即会解除删除)
	MsgId_C2S_ServerList       MsgId = 10 // 请求服务器列表
	MsgId_C2S_AnnouncementList MsgId = 11 // 请求公告列表
	MsgId_C2S_SelectServer     MsgId = 12 // 选择服务器
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:  "Msg_None",
		1:  "C2S_SignIn",
		2:  "C2S_DeleteAccount",
		10: "C2S_ServerList",
		11: "C2S_AnnouncementList",
		12: "C2S_SelectServer",
	}
	MsgId_value = map[string]int32{
		"Msg_None":             0,
		"C2S_SignIn":           1,
		"C2S_DeleteAccount":    2,
		"C2S_ServerList":       10,
		"C2S_AnnouncementList": 11,
		"C2S_SelectServer":     12,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_login_id_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_login_id_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_login_id_proto_rawDescGZIP(), []int{0}
}

var File_login_id_proto protoreflect.FileDescriptor

var file_login_id_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x2a, 0x80, 0x01, 0x0a, 0x05, 0x4d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x5f, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x32, 0x53,
	0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x0a, 0x12, 0x18, 0x0a,
	0x14, 0x43, 0x32, 0x53, 0x5f, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x0b, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x5f, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x0c, 0x42, 0x16, 0x5a,
	0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_login_id_proto_rawDescOnce sync.Once
	file_login_id_proto_rawDescData = file_login_id_proto_rawDesc
)

func file_login_id_proto_rawDescGZIP() []byte {
	file_login_id_proto_rawDescOnce.Do(func() {
		file_login_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_id_proto_rawDescData)
	})
	return file_login_id_proto_rawDescData
}

var file_login_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_login_id_proto_goTypes = []interface{}{
	(MsgId)(0), // 0: login_id.MsgId
}
var file_login_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_id_proto_init() }
func file_login_id_proto_init() {
	if File_login_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_id_proto_goTypes,
		DependencyIndexes: file_login_id_proto_depIdxs,
		EnumInfos:         file_login_id_proto_enumTypes,
	}.Build()
	File_login_id_proto = out.File
	file_login_id_proto_rawDesc = nil
	file_login_id_proto_goTypes = nil
	file_login_id_proto_depIdxs = nil
}
