// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: login/msg.proto

package msg

import (
	comm "github.com/njtc406/chaosengine/example/msg/comm"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @id: 1 C2S_SignIn 登录
type C2S_SignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`         // 用户名
	Password     string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`         // 密码
	Token        string `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`               // token
	Type         string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`                 // 校验类型(local guest sdk_name)
	Channel      string `protobuf:"bytes,5,opt,name=Channel,proto3" json:"Channel,omitempty"`           // 渠道
	ChildChannel string `protobuf:"bytes,6,opt,name=ChildChannel,proto3" json:"ChildChannel,omitempty"` // 子渠道
}

func (x *C2S_SignIn) Reset() {
	*x = C2S_SignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SignIn) ProtoMessage() {}

func (x *C2S_SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SignIn.ProtoReflect.Descriptor instead.
func (*C2S_SignIn) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_SignIn) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *C2S_SignIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *C2S_SignIn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2S_SignIn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *C2S_SignIn) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *C2S_SignIn) GetChildChannel() string {
	if x != nil {
		return x.ChildChannel
	}
	return ""
}

type S2C_SignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // 登录token(用于进入游戏时的验证,返回0时才有这个)
}

func (x *S2C_SignIn) Reset() {
	*x = S2C_SignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SignIn) ProtoMessage() {}

func (x *S2C_SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SignIn.ProtoReflect.Descriptor instead.
func (*S2C_SignIn) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_SignIn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// @id: 2 C2S_DeleteAccount 注销账号
type C2S_DeleteAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *C2S_DeleteAccount) Reset() {
	*x = C2S_DeleteAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_DeleteAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DeleteAccount) ProtoMessage() {}

func (x *C2S_DeleteAccount) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DeleteAccount.ProtoReflect.Descriptor instead.
func (*C2S_DeleteAccount) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_DeleteAccount) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2C_DeleteAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteTime int64 `protobuf:"varint,1,opt,name=DeleteTime,proto3" json:"DeleteTime,omitempty"` // 删除账号时间
}

func (x *S2C_DeleteAccount) Reset() {
	*x = S2C_DeleteAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_DeleteAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DeleteAccount) ProtoMessage() {}

func (x *S2C_DeleteAccount) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DeleteAccount.ProtoReflect.Descriptor instead.
func (*S2C_DeleteAccount) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_DeleteAccount) GetDeleteTime() int64 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

// @id: 10 C2S_ServerList 请求服务器列表
type C2S_ServerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *C2S_ServerList) Reset() {
	*x = C2S_ServerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ServerList) ProtoMessage() {}

func (x *C2S_ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ServerList.ProtoReflect.Descriptor instead.
func (*C2S_ServerList) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_ServerList) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2C_ServerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ServerInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // 服务器列表
}

func (x *S2C_ServerList) Reset() {
	*x = S2C_ServerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ServerList) ProtoMessage() {}

func (x *S2C_ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ServerList.ProtoReflect.Descriptor instead.
func (*S2C_ServerList) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_ServerList) GetList() []*ServerInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// @id: 11 C2S_AnnouncementList 请求公告列表
type C2S_AnnouncementList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *C2S_AnnouncementList) Reset() {
	*x = C2S_AnnouncementList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_AnnouncementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_AnnouncementList) ProtoMessage() {}

func (x *C2S_AnnouncementList) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_AnnouncementList.ProtoReflect.Descriptor instead.
func (*C2S_AnnouncementList) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_AnnouncementList) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2C_AnnouncementList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AnnouncementInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // 公告列表
}

func (x *S2C_AnnouncementList) Reset() {
	*x = S2C_AnnouncementList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_AnnouncementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AnnouncementList) ProtoMessage() {}

func (x *S2C_AnnouncementList) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AnnouncementList.ProtoReflect.Descriptor instead.
func (*S2C_AnnouncementList) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_AnnouncementList) GetList() []*AnnouncementInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// @id: 12 C2S_SelectServer 选择服务器
type C2S_SelectServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32  `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"` // 服务器ID
	Token    string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`        // 验证返回的那个token
}

func (x *C2S_SelectServer) Reset() {
	*x = C2S_SelectServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_SelectServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_SelectServer) ProtoMessage() {}

func (x *C2S_SelectServer) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_SelectServer.ProtoReflect.Descriptor instead.
func (*C2S_SelectServer) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_SelectServer) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *C2S_SelectServer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2C_SelectServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"` // 服务器地址
}

func (x *S2C_SelectServer) Reset() {
	*x = S2C_SelectServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_SelectServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SelectServer) ProtoMessage() {}

func (x *S2C_SelectServer) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SelectServer.ProtoReflect.Descriptor instead.
func (*S2C_SelectServer) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_SelectServer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32             `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                       // 服务器ID
	Name      string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                                    // 服务器名称
	StartTime int64             `protobuf:"varint,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`                         // 服务器开服时间
	Status    comm.ServerStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=common_comm.ServerStatus" json:"Status,omitempty"` // 服务器状态
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{10}
}

func (x *ServerInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ServerInfo) GetStatus() comm.ServerStatus {
	if x != nil {
		return x.Status
	}
	return comm.ServerStatus(0)
}

type AnnouncementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`            // 标题
	Content    string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`        // 内容
	Group      string `protobuf:"bytes,3,opt,name=Group,proto3" json:"Group,omitempty"`            // 群组
	ShowTime   int64  `protobuf:"varint,4,opt,name=ShowTime,proto3" json:"ShowTime,omitempty"`     // 显示时间
	ExpireTime int64  `protobuf:"varint,5,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"` // 过期时间
	Sort       int32  `protobuf:"varint,6,opt,name=Sort,proto3" json:"Sort,omitempty"`             // 排序
	Url        string `protobuf:"bytes,7,opt,name=Url,proto3" json:"Url,omitempty"`                // 链接地址
}

func (x *AnnouncementInfo) Reset() {
	*x = AnnouncementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementInfo) ProtoMessage() {}

func (x *AnnouncementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementInfo.ProtoReflect.Descriptor instead.
func (*AnnouncementInfo) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{11}
}

func (x *AnnouncementInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnnouncementInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AnnouncementInfo) GetShowTime() int64 {
	if x != nil {
		return x.ShowTime
	}
	return 0
}

func (x *AnnouncementInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *AnnouncementInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *AnnouncementInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_login_msg_proto protoreflect.FileDescriptor

var file_login_msg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x1a, 0x0f, 0x63, 0x6f,
	0x6d, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01,
	0x0a, 0x0a, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x43, 0x68, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x22, 0x0a, 0x0a,
	0x53, 0x32, 0x43, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x29, 0x0a, 0x11, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x33, 0x0a, 0x11, 0x53,
	0x32, 0x43, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x26, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3b, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x14, 0x43, 0x32, 0x53, 0x5f, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x14, 0x53, 0x32, 0x43, 0x5f, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x10,
	0x43, 0x32, 0x53, 0x5f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x81, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x31, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72,
	0x6c, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x73, 0x67, 0x2f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_login_msg_proto_rawDescOnce sync.Once
	file_login_msg_proto_rawDescData = file_login_msg_proto_rawDesc
)

func file_login_msg_proto_rawDescGZIP() []byte {
	file_login_msg_proto_rawDescOnce.Do(func() {
		file_login_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_msg_proto_rawDescData)
	})
	return file_login_msg_proto_rawDescData
}

var file_login_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_login_msg_proto_goTypes = []interface{}{
	(*C2S_SignIn)(nil),           // 0: login_msg.C2S_SignIn
	(*S2C_SignIn)(nil),           // 1: login_msg.S2C_SignIn
	(*C2S_DeleteAccount)(nil),    // 2: login_msg.C2S_DeleteAccount
	(*S2C_DeleteAccount)(nil),    // 3: login_msg.S2C_DeleteAccount
	(*C2S_ServerList)(nil),       // 4: login_msg.C2S_ServerList
	(*S2C_ServerList)(nil),       // 5: login_msg.S2C_ServerList
	(*C2S_AnnouncementList)(nil), // 6: login_msg.C2S_AnnouncementList
	(*S2C_AnnouncementList)(nil), // 7: login_msg.S2C_AnnouncementList
	(*C2S_SelectServer)(nil),     // 8: login_msg.C2S_SelectServer
	(*S2C_SelectServer)(nil),     // 9: login_msg.S2C_SelectServer
	(*ServerInfo)(nil),           // 10: login_msg.ServerInfo
	(*AnnouncementInfo)(nil),     // 11: login_msg.AnnouncementInfo
	(comm.ServerStatus)(0),       // 12: common_comm.ServerStatus
}
var file_login_msg_proto_depIdxs = []int32{
	10, // 0: login_msg.S2C_ServerList.List:type_name -> login_msg.ServerInfo
	11, // 1: login_msg.S2C_AnnouncementList.List:type_name -> login_msg.AnnouncementInfo
	12, // 2: login_msg.ServerInfo.Status:type_name -> common_comm.ServerStatus
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_login_msg_proto_init() }
func file_login_msg_proto_init() {
	if File_login_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_login_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_SignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_SignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_DeleteAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_DeleteAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_ServerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_ServerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_AnnouncementList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_AnnouncementList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_SelectServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_SelectServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_msg_proto_goTypes,
		DependencyIndexes: file_login_msg_proto_depIdxs,
		MessageInfos:      file_login_msg_proto_msgTypes,
	}.Build()
	File_login_msg_proto = out.File
	file_login_msg_proto_rawDesc = nil
	file_login_msg_proto_goTypes = nil
	file_login_msg_proto_depIdxs = nil
}
