# http服务

# gm端口配置(用于gm后台通讯)
GmServerConf:
  Addr: 0.0.0.0:81
  ReadHeaderTimeout: 10s
  IdleTimeout: 30s
  #CachePath: http_cache
  # 开启鉴权
  Auth: false
  Account:
    root: 123456

GmAddr: 127.0.0.1:8888